version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: wine_db
      POSTGRES_USER: wine_user
      POSTGRES_PASSWORD: wine_pass
    ports:
      - "5432:5432"
    networks:
      - shared_network  # Connecting to the shared network for PostgreSQL

  web:
    build: .
    command: ["wait-for-it", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - shared_network  # Shared network for communication with Node

networks:
  shared_network:
    external: true  # Using the same external shared network