# Generated by Django 3.2 on 2024-11-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('grape_variety', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='preferences.winepreference')),
            ],
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
