# Generated by Django 4.2.16 on 2024-11-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_auto_20241101_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrapeRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('famous_for', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
