# Generated by Django 4.2.16 on 2024-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_graperegion'),
    ]

    operations = [
        migrations.AddField(
            model_name='graperegion',
            name='country_code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
