# Generated by Django 4.2.16 on 2024-11-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_graperegion_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graperegion',
            name='country_code',
            field=models.CharField(blank=True, help_text='Código do país', max_length=5),
        ),
    ]
